# initially copied from https://github.com/harshjv/travis-ci-latex-pdf/blob/master/.travis.yml
sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-pictures libgit2* 
- wget https://github.com/XimeraProject/xake/releases/download/v0.9.4/xake_0.9.4_amd64.deb
- sudo dpkg -i xake_0.9.4_amd64.deb
- mkdir -p ~/texmf/tex/latex
- (cd ~/texmf/tex/latex ; git clone https://github.com/XimeraProject/ximeraLatex.git )
script:
- ~/go/bin/xake bake
- ~/go/bin/xake frost
